added convenient methods on respond
FlorianUekermann/async-web-client pull request #13
Opened 2024-11-06 20:08 UTC by sin-sch

- add function for read bytes
- convert bytes into string
- convert string in json
- edit post example: now using the new json method

2024-11-10 15:52 UTC, FlorianUekermann commented
fixes #7

2024-11-10 16:31 UTC, FlorianUekermann requested changes

2024-11-10 16:31 UTC, FlorianUekermann commented on src/http/mod.rs
> +    pub async fn bytes(&mut self) -> Result<Vec<u8>, io::Error> {
Let's add `limit: Option<usize>` to this and the other two methods using `take()`.
Implementation can be mostly copied from `body_vec` a few lines above.

All methods in ResponseExt can be removed.

2024-11-10 16:31 UTC, FlorianUekermann commented on src/http/mod.rs
> +        let bytes = self.bytes().await?;
Implement directly using `read_to_string`. That should be more efficient by catching encoding issues without reading the whole body first.

2024-11-17 20:30 UTC, sin-sch commented on src/http/mod.rs
> +        let bytes = self.bytes().await?;
We may not need the `bytes` method then. We do not use it in the `string` anymore, if we use `read_to_string` instead.

2024-11-17 20:44 UTC, FlorianUekermann commented on src/http/mod.rs
> +        let bytes = self.bytes().await?;
`bytes` is intended to be used directly by users as well

2024-11-28 13:55 UTC, FlorianUekermann requested changes

2024-11-28 13:55 UTC, FlorianUekermann commented on src/http/mod.rs
> +//use async_net::TcpStream;
leftover, there are a couple of others like this

2024-11-28 13:55 UTC, FlorianUekermann commented on Cargo.toml
> +reqwest = "0.12.7"
accidental dependency?

2024-11-28 13:55 UTC, FlorianUekermann commented on Cargo.toml
remove empty line

2024-11-28 13:55 UTC, FlorianUekermann commented on Cargo.toml
> +serde_json = "1.0"
let's make these optional and add a `json` feature flag, which is enabled by default, see chat message from Nov 10 for details

2024-12-19 15:24 UTC, merged