update yml file
FlorianUekermann/async-web-client pull request #18
Opened 2024-12-21 12:23 UTC by sin-sch

Issue #14 and #15
Add Clippy and cargo fmt --check to yml file

2024-12-22 09:51 UTC, FlorianUekermann requested changes
We need to actually fix the clippy warnings in this PR as well.

2024-12-22 09:51 UTC, FlorianUekermann commented on .github/workflows/rust.yml
> +      - run: cargo clippy --tests --no-default-features --features ${{ matrix.crypto }},${{ matrix.ws }}, ${{ matrix.json }}
remove extra space after comma

2024-12-22 09:51 UTC, FlorianUekermann commented on .github/workflows/rust.yml
> +      - run: rustup component add cargofmt
I think it's `rustfmt`

2024-12-22 09:51 UTC, FlorianUekermann commented on .github/workflows/rust.yml
>        - run: cargo test --verbose --features ${{ matrix.crypto }},${{ matrix.ws }},${{ matrix.json }}
I guess we should also add --no-default-features here.

2025-01-09 12:40 UTC, sin-sch commented on .github/workflows/rust.yml
>        - run: cargo test --verbose --features ${{ matrix.crypto }},${{ matrix.ws }},${{ matrix.json }}
I thiink for compilation we need the `aws-lc-rs` feature.

2025-01-15 15:41 UTC, merged